import { safe, list } from '../utils/html.js';
export function professorDomain(level, domains) { return domains[level.domain] || `הפרק הזה עוסק ב-${level.domain}. לפני מדידה וניתוח, צריך להבין את המנגנון הכלכלי והטכני שמייצר את הנתונים.`; }
export function professorLecture(level, topic, domains) {
    const d = topic.deep || {};
    const w = d.worked_example || {};
    const interp = Array.isArray(d.interpret) ? d.interpret : [];
    const red = Array.isArray(d.red) ? d.red : [];
    const formula = topic.formula || d.formula || '';
    return `<div id="lecture" class="professor-full"><span class="lecture-badge">PROFESSOR LECTURE</span><span class="lecture-badge">חובה לפני Analyst Layer</span><div class="lecture-title">${topic.name}</div><div class="lecture-subtitle">המטרה כאן היא ללמוד את הרעיון כאילו זו הפעם הראשונה שאתה פוגש אותו. רק אחרי שהמנגנון ברור עוברים לדאשבורדים, ratios, workflow ומסקנות השקעה.</div><div class="lecture-path"><span>1 · מה הבעיה?</span><span>2 · איך זה עובד?</span><span>3 · דוגמה</span><span>4 · למה למשקיע?</span><span>5 · איפה טועים?</span><span>6 · Teach-back</span></div>
<div class="teach-card teacher-voice"><h3>1. לפני הכול — מה אנחנו בכלל לומדים?</h3><p>${professorDomain(level, domains)}</p><p class="keyline">עכשיו מצמצמים את תמונת העל לשאלה אחת: מה בדיוק <strong>${topic.name}</strong> עוזר לנו להבין?</p><p>${safe(d.definition || topic.definition)}</p><p>אל תחשוב על המושג כעל KPI שצריך לזכור. תחשוב עליו כעל <strong>עדשה</strong>: הוא לוקח חלק מסוים מהמערכת ומנסה לענות על שאלה שלא ניתן לענות עליה רק ממחיר הטוקן.</p></div>
<div class="teach-card mechanism-v9"><h3>2. האינטואיציה והמנגנון, צעד-אחר-צעד</h3><p>${safe(d.mental)}</p><p>${safe(d.why)}</p>${topic.method ? `<p><strong>איך בודקים את זה בפועל:</strong> ${topic.method}</p>` : ''}${formula ? `<div class="formula">${formula}</div><p><strong>איך לקרוא נוסחה:</strong> זהה קודם את המונה, המכנה/היצע, היחידות וחלון הזמן.</p>` : ''}<p>המבחן כאן הוא causal: מה צריך לקרות במערכת כדי שהמדד יעלה או ירד?</p></div>
<div class="teach-card worked-v9"><h3>3. דוגמה מודרכת — המרצה חושב בקול</h3><p><strong>התרחיש:</strong> ${safe(w.prompt || topic.exercise)}</p><p><strong>פתרון מודרך:</strong> ${safe(w.solution)}</p><p><strong>מה המרצה רוצה שתראה:</strong> ${safe(w.lesson)}</p><p><strong>חשיבה בקול:</strong> קודם מוודאים שהנתון מודד את מה שאנחנו חושבים שהוא מודד. אחר כך משווים לעבר/peers, ורק לבסוף מחברים לתזה.</p></div>
<div class="teach-card investment-v9"><h3>4. איך זה מתחבר לניתוח השקעה?</h3><p><strong>למה למשקיע אכפת?</strong> ${safe(d.why)}</p>${interp.length ? `<p><strong>דרך קריאה נכונה:</strong></p>${list(interp, 4)}` : ''}<p>שאל איזו חוליה בתזה מתעדכנת: ביקוש, economics, value capture, dilution, liquidity, moat, valuation או risk.</p></div>
<div class="teach-card limits-v9"><h3>5. למה אפשר לטעות גם עם מספר נכון?</h3><p><strong>המלכודת הראשית:</strong> ${safe(topic.trap || red[0])}</p>${red.length ? list(red, 6) : ''}<p>נתון יכול להיות נכון עובדתית ועדיין להיות ראיה חלשה בגלל הגדרה, denominator, price effect, incentives או cohort לא מתאים.</p></div>
<div class="teach-card teachback-v9"><h3>6. בדיקת הבנה אמיתית — Teach-back</h3><ol><li>הסבר את <strong>${topic.name}</strong> לאדם חכם שלא מכיר קריפטו.</li><li>תן דוגמה למצב שבו המדד נראה חיובי אבל הכלכלה לא השתפרה.</li><li>איזה נתון שני היית מצרף אליו?</li><li>מה היה גורם לך לומר שהנתון לא מספיק לעדכון התזה?</li></ol><p><b>אם אינך יכול לענות על ארבע השאלות, אל תעבור עדיין ל-Analyst Layer.</b></p></div>
<div class="teacher-note"><b>הערת מרצה:</b> המטרה היא שתוכל להסביר את המושג, המנגנון והמגבלות שלו לפני שאתה משתמש בו כראיה.</div><div class="bridge"><b>מוכן לעבור לניתוח?</b> עכשיו מגיע Analyst Layer. <button class="btn green" data-action="jump" data-target="theory">המשך ל-Analyst Layer ↓</button></div></div>`;
}
export function chapterLecture(level, domains) { const names = level.topics.map((t, i) => `${i + 1}. ${t.name}`); return `<div class="chapter-lecture-v9"><span class="lecture-badge">LECTURE 0</span><span class="lecture-badge">מבוא לפרק</span><h2>לפני Topic 1 — להבין את המפה של ${level.title}</h2><div class="chapter-step"><h3>למה בכלל התחום הזה קיים?</h3><p>${professorDomain(level, domains)}</p><p><strong>בסוף הפרק אתה אמור לדעת:</strong> ${level.obj}</p></div><div class="chapter-step"><h3>איזו בעיה אנליטית אנחנו פותרים?</h3><p>מחיר לבדו לא מספר לנו למה נכס קיים, מי יוצר את הערך, מי לוכד אותו ומה עלול לשחוק אותו. הפרק מפרק את הבעיה לחלקים קטנים.</p></div><div class="chapter-step"><h3>מסלול הלמידה</h3><div class="concept-map">${names.map(x => `<span class="concept-node">${x}</span>`).join('<span class="concept-arrow">←</span>')}</div><p>אל תדלג קדימה רק כי אתה מכיר שם של KPI. המטרה היא להבין מדוע כל שלב קיים ואיזה input הוא נותן לשלב הבא.</p></div><div class="chapter-step"><h3>מה לא עושים</h3><p>לא מתחילים מ-dashboard, לא מחפשים מספר "טוב", ולא מסיקים bullish/bearish ממשתנה בודד.</p></div></div>`; }
