import { academyPct, levelProgress, topicProgress } from '../features/learning/mastery.js';
import { progressBar } from '../utils/html.js';
import { progressStore } from '../store/progressStore.js';
export function badge(level) { const p = levelProgress(level); if (p.passed && p.done === p.total)
    return `<span class="status st2">PASSED</span>`; if (p.done > 0 || progressStore.state.chapterExams[String(level.n)]?.attempted)
    return `<span class="status st1">IN PROGRESS</span>`; return `<span class="status st0">NOT STARTED</span>`; }
export function chapterCard(m, level) { const p = levelProgress(level); return `<div class="card"><div class="ctop"><div class="chips"><span class="chip">LEVEL ${level.n}</span><span class="chip">${level.domain}</span></div>${badge(level)}</div><h3>${level.title}</h3><div class="muted">${level.obj}</div><div style="margin-top:9px">${progressBar(p.pct)}</div><div class="small">${p.done}/${p.total} נושאים Mastered · Exam ${p.passed ? '✓' : '—'}</div><div class="actions"><button class="btn" data-route="level/${level.n}">פתח פרק</button><button class="btn alt" data-route="exam/${level.n}">מבחן</button></div></div>`; }
export function academies(m) { return m.academies.map((a) => { const p = academyPct(m, a[2]); return `<div class="academy"><div class="ahead"><h3>Academy ${a[0]} — ${a[1]}</h3><div style="flex:1">${progressBar(p)}</div><b>${p}%</b></div><div class="chapters">${a[2].map((n) => chapterCard(m, m.levels.find(l => l.n === n))).join('')}</div></div>`; }).join(''); }
export function topicRow(levelId, i, t) { const p = topicProgress(levelId, i); return `<div class="topicrow ${p.done ? 'done' : ''}"><input type="checkbox" ${p.done ? 'checked' : ''} disabled><div><b>${i + 1}. ${t.name}</b><div class="small">${t.definition}</div><div style="margin-top:6px">${progressBar(p.pct)}</div></div><div class="actions"><button class="btn" data-route="topic/${levelId}/${i}">למד</button><span class="chip">${p.score}% exam</span></div></div>`; }
